# Generated by Django 5.2.6 on 2025-09-17 00:02

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('scolarite', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='bulletin',
            field=models.FileField(blank=True, null=True, upload_to='demandes/bulletins/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='dernier_diplome',
            field=models.FileField(blank=True, null=True, upload_to='demandes/diplomes/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='demandes/photos/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='salle',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='etablissement', chained_model_field='batiment__etablissement', default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.salle'),
            preserve_default=False,
        ),
    ]
