# Generated by Django 5.2.6 on 2025-09-17 01:12

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('scolarite', '0003_demande_bulletin_demande_dernier_diplome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='salle',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='etablissement', chained_model_field='batiment__etablissement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.salle'),
        ),
    ]
