# Generated by Django 5.2.6 on 2025-09-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='nom',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etablissement',
            name='nom',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
